export const subjects = [
  "App Development",
  "Data Analysis",
  "Web Development and Landing Pages",
  "Search Engine Optimization",
  "User Experience Design",
  "Advertising Strategy",
  "UI and Ux Design",
  "Digital Marketing",
  "Software Engineering",
  "Agentic Programming",
  "Artificial Intelligence",
  "Cloud Computing",
  "Cybersecurity",
  "Blockchain Technology",
  "Mobile App Development",
  "Google Ads and PPC",
  "Social Media Marketing",
  "Content Marketing",
  "Email Marketing",
  "E-commerce and Online Sales",
  "Data Visualization",
  "Machine Learning",
  "Natural Language Processing",
];

export const subjectsColors = {
  "App Development":"#E5D0FF",
  "Data Analysis":"#E5D0FF",
  "Web Development and Landing Pages":"#E5D0FF",
  "Search Engine Optimization":"#E5D0FF",
  "User Experience Design":"#E5D0FF",
  "Advertising Strategy":"#E5D0FF",
  "UI and Ux Design":"#E5D0FF",
  "Digital Marketing":"#E5D0FF",
  "Software Engineering":"#E5D0FF",
  "Agentic Programming":"#E5D0FF",
  "Artificial Intelligence":"#E5D0FF",
  "Cloud Computing":"#E5D0FF",
  "Cybersecurity":"#E5D0FF",
  "Blockchain Technology":"#E5D0FF",
  "Mobile App Development":"#E5D0FF",
  "Google Ads and PPC":"#E5D0FF",
  "Social Media Marketing":"#E5D0FF",
  "Content Marketing":"#E5D0FF",
  "Email Marketing":"#E5D0FF",
  "E-commerce and Online Sales":"#E5D0FF",
  "Data Visualization":"#E5D0FF",
  "Machine Learning":"#E5D0FF",
  "Natural Language Processing":"#E5D0FF",

};

export const voices = {
  male: { casual: "2BJW5coyhAzSr8STdHbE", formal: "c6SfcYrb2t09NHXiT80T" },
  female: { casual: "ZIlrSGI4jZqobxRKprJz", formal: "sarah" },
};

export const recentSessions = [
  {
    id: "1",
    subject: "Math",
    name: "Neura the Brainy Explorer",
    topic: "Neural Network of the Brain",
    duration: 45,
    color: "#E5D0FF",
  },
  {
    id: "2",
    subject: "Physics",
    name: "Countsy the Number Wizard",
    topic: "Derivatives & Integrals",
    duration: 30,
    color: "#FFDA6E",
  },
  {
    id: "3",
    subject: "Chemistry",
    name: "Verba the Vocabulary Builder",
    topic: "English Literature",
    duration: 30,
    color: "#BDE7FF",
  },
  {
    id: "4",
    subject: "Biology",
    name: "Codey the Logic Hacker",
    topic: "Intro to If-Else Statements",
    duration: 45,
    color: "#FFC8E4",
  },
  {
    id: "5",
    subject: "Astronomy",
    name: "Memo, the Memory Keeper",
    topic: "World Wars: Causes & Consequences",
    duration: 15,
    color: "#FFECC8",
  },
  {
    id: "6",
    subject: "Particle Physics",
    name: "The Market Maestro",
    topic: "The Basics of Supply & Demand",
    duration: 10,
    color: "#C8FFDF",
  },
];
